project:
    name: titanic-mlops-projects_1


# deployments:
#     - env: dev
#       executor: celery
#       image:
#         name: quay.io/astronomer/astro-runtime:7.3.0
#       name: dev
# mounts:
#     - source: ./shared
#       target: /usr/local/airflow/shared

