# Use the official Python image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements and install them
COPY requirements2.txt .
RUN pip install --no-cache-dir -r requirements2.txt

# Copy the Streamlit app
COPY . .

# Expose the port Streamlit will run on
EXPOSE 8501

# Command to run Streamlit
CMD ["streamlit", "run", "app.py", "--server.port", "8501", "--server.headless", "true"]
