# Use the official Python image
FROM python:3.9-slim

WORKDIR /app

COPY requirements2.txt .

RUN pip install --no-cache-dir -r requirements2.txt

# Copy all app code and artifacts folder including model
COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
